# Demographics {#dem}

```{r full-data, echo=FALSE}
nsfg <- readRDS("~/NSFG_DATA/Full/nsfg_complete.rds")
svy <- as_survey_design(nsfg, weights = weight, ids = CASEID)
```

The combined datasets from 2006-2015 include data from `r nsfg %>% count()` respondents. 


## Sex & Age 

```{r full-age, echo=FALSE}
#p2 <- svy %>% group_by(sex, age) %>% summarize(count=survey_total()) 
#p2 <- dcast(p2, age~sex, value.var="count")
  
#p2 %>% 
#  plot_ly(x=~age, y=~`F`, type="bar", name="Females") %>%
#  add_trace(x=~age, y=~M, type="bar", name="Males") %>%
#    layout(yaxis = list(title="", barmode='group'), 
#         xaxis = list(title=""),
#         title = "Counts, by Age & Sex")

p3 <- svy %>% group_by(sex, agecat) %>% summarize(count=survey_total()) 
p3 <- dcast(p3, agecat~sex, value.var="count")
  
p3 %>% 
  plot_ly(x=~agecat, y=~`F`, type="bar", name="Females") %>%
  add_trace(x=~agecat, y=~M, type="bar", name="Males") %>%
    layout(yaxis = list(title="", barmode='group'), 
         xaxis = list(title=""),
         title = "Counts, by Age & Sex")
```

## Race
```{r racesex, echo = FALSE} 
rw <- svy %>% group_by(sex, race) %>% summarize(n=survey_total())
rw <- dcast(rw, race~sex, value.var = "n")
rw %>% plot_ly(x=~race, y=~`F`, type = 'bar', name="Females") %>% 
        add_trace(x=~race, y=~M, name="Males") %>%
        layout(title = "Counts by Race & Sex")
```

## Age Category & Race
```{r full-agerace, echo=FALSE}
arw <- svy %>% group_by(agecat, race) %>% summarize(count=survey_total())
arw <- dcast(arw, agecat~race, value.var = "count")

arw %>% plot_ly(x=~agecat, y=~b, type='bar', name="Black") %>%
          add_trace(x=~agecat, y=~h, name="Hispanic") %>%
          add_trace(x=~agecat, y=~w, name="White") %>%
          add_trace(x=~agecat, y=~o, name="Other") %>%
          layout(yaxis = list(title="", barmode='group'), 
               xaxis = list(title=""), title="Counts by AgeCat & Race")
```



## Unweighted Counts 

```{r pops, echo=FALSE}
age.raceF <- nsfg %>% filter(sex %in% "F") %>% count(agecat, race)
age.raceM <- nsfg %>% filter(sex %in% "M") %>% count(agecat, race)
Fem <- dcast(age.raceF, agecat~race, value.var = "n")
Male <- dcast(age.raceM, agecat~race, value.var = "n")
```
### Females
```{r fempop, echo=FALSE}
kable(Fem, title="Females") %>% kable_styling(position="center", full_width = F)
```
### Males
```{r malepop, echo=FALSE}
kable(Male, title="Males") %>% kable_styling(position="center", full_width = F)
```
