# Egos - Partnerships {#subset}

```{r load-altersedgelist, echo=FALSE}
dat <- readRDS("../data/alters_egos.rds")
datsvy <- as_survey_design(dat, weights = e.weight, ids = ego)
```
## Active Vars
### Raw Counts  
```{r actives, echo=FALSE}
actives <- dat %>% group_by(e.sex) %>% count(active)
actives <- dcast(actives, active~e.sex, value.var = "n")
actives[,1] <- c("0-Inactive", "1-Active", "2-No sex lstyr","6-Fewer Partners", "8-Never had sex", "9-Miss/Ref/Dk")

actives %>% plot_ly(x=~active, y=~`F`, type="bar", name="Females") %>%
  add_trace(x=~active, y=~M, name="Males") %>%
  layout(title="All Partner Statuses By Ego Sex (3 per ego)",
         xaxis=list(title=""),
         yaxis=list(title=""))

# weighted
#actives2 <- datsvy %>% 
```



### Weighted counts (in progress, srvyr issues)
```{r weightedactives, echo=FALSE}
#a1w <- svy %>% group_by(sex) %>% summarize(n=survey_total(active1))
#a1 <- dcast(a1, active1~sex, value.var = "n")
#a1$active1 <- c("0-Inactive", "1-Active", "2-No sex lstyr", "8-Never had sex", "9-Miss/Ref/Dk")
#a1p <- a1 %>% plot_ly(x=~active1, y=~`F`, type='bar', name="Females") %>%
#  add_trace(x=~active1, y=~M, name="Males") %>%
#  layout(title="1st Partner by EgoSex (counts)",
#         xaxis=list(title=""),
#         yaxis=list(title="1st"), showlegend=F)
``` 

## parts1yr 
```{r parts1yr, echo=FALSE}



```

## other ego vars
rel types ('optype')
life partners? 
sex group by age / have had ss contact by age 
had sex by age 
