# Relationships Overview {#allrels}

## Sexual Activty in Last Year
### Females  
```{r activity-graph-females, echo=FALSE}
actF <- svy %>% filter(sex %in% "F") %>%
                mutate(act = ifelse(HADSEX == 2, "1", 
                            ifelse(PARTS1YR == 0, "2", 
                            ifelse(PARTS1YR > 0, "3", NA)))) %>%
                group_by(agecat, act) %>% 
                summarize(n=survey_total()) %>%
                group_by(agecat) %>%
                mutate(prop = n/sum(n))
actF <- dcast(actF, agecat~act, value.var = "prop")



actF %>% plot_ly(x=~agecat, y=~`1`, type='bar', name='Never Sex') %>%
          add_trace(y=~`2`, type='bar', name = "Inactive") %>%
          add_trace(y=~`3`, type='bar', name = "Active") %>%
          layout(title = "Sexual Activity by Age, Females", 
                 yaxis = list(title="Proportion"),
                 xaxis = list(title="Age Category"))


```  


### Males  

```{r sexual-activity-males, echo=FALSE}
actM <- svy %>% filter(sex %in% "M") %>%
                mutate(act = ifelse(HADSEX == 2, "1", 
                            ifelse(PARTS1YR == 0, "2", 
                            ifelse(PARTS1YR > 0, "3", NA)))) %>%
                group_by(agecat, act) %>% 
                summarize(n=survey_total()) %>%
                group_by(agecat) %>%
                mutate(prop = n/sum(n))
actM <- dcast(actM, agecat~act, value.var = "prop")

actM %>% plot_ly(x=~agecat, y=~`1`, type='bar', name='Never Sex') %>%
          add_trace(y=~`2`, type='bar', name = "Inactive") %>%
          add_trace(y=~`3`, type='bar', name = "Active") %>%
          layout(title = "Sexual Activity by Age, Males", 
                 yaxis = list(title="Proportion"),
                 xaxis = list(title="Age Category"))
```



## Partnerships in Last Year 

```{r parts1yr, echo=FALSE}
partsyr <- suppressWarnings(svy %>% 
                              filter(PARTS1YR >= 0) %>% 
                              group_by(PARTS1YR) %>% 
                              summarize(n=survey_total()))

partsyr$PARTS1YR <- as.numeric(partsyr$PARTS1YR)
partsyr <- partsyr[order(partsyr$PARTS1YR),] 

partsyr %>% plot_ly(x=~PARTS1YR, y=~n, type="bar") %>%
            layout(title="parts. in last year among those who have had sex")

datatable(round(partsyr, 0))
```

```{r prop4, echo=FALSE, results='hide'}
props <- suppressWarnings(svy %>% 
                            mutate(parts_prop = ifelse(as.numeric(vsnpyr) < 4, 1, 
                            ifelse(as.numeric(vsnpyr) >= 4, 2, NA))) %>%
                            group_by(parts_prop) %>% 
                            summarize(n=survey_total()) %>%
                            mutate(prop = n/sum(n)))

propF <- suppressWarnings(svy %>% 
                            filter(sex %in% 'F') %>%
                            mutate(parts_prop = ifelse(as.numeric(vsnpyr) < 4, 1, 
                            ifelse(as.numeric(vsnpyr) >= 4, 2, NA))) %>%
                            group_by(parts_prop) %>% 
                            summarize(n=survey_total()) %>%
                            mutate(prop = n/sum(n)))

propM <- suppressWarnings(svy %>% 
                            filter(sex %in% 'M') %>%
                            mutate(parts_prop = ifelse(as.numeric(vsnpyr) < 4, 1, 
                            ifelse(as.numeric(vsnpyr) >= 4, 2, NA))) %>%
                            group_by(parts_prop) %>% 
                            summarize(n=survey_total()) %>%
                            mutate(prop = n/sum(n)))
```

Only `r props[2,4]*100`% of respondents report more than 3 partnership in the last year.  
`r propF[2,4]*100`% of Females  
`r propM[2,4]*100`% of Males  


## Ever Married or Cohabitated 
### Overall  
```{r evmarcoh, echo=FALSE}
evmar <- suppressWarnings(svy %>% 
          group_by(agecat, EVMARCOH) %>% 
          summarize(count=survey_total()))
evmar <- dcast(evmar, agecat~EVMARCOH, value.var = "count")
evmar$prop <- evmar$`1` / (evmar$`1` + evmar$`2`) 

evmar %>% plot_ly(x=~agecat, y=~prop, type='bar') %>%
          layout(yaxis = list(title="Proportion"), 
               xaxis = list(title="Age Category"), title="Ever Married or Cohabitated")

```
### By Sex  
```{r evmar-sex, echo=FALSE}
evmarSex <- suppressWarnings(svy %>% 
              group_by(agecat, sex, EVMARCOH) %>% 
              summarize(count=survey_total())) 
evmarSex <- dcast(evmarSex, agecat+sex~EVMARCOH, value.var = "count")
evmarSex$prop <- evmarSex$`1` / (evmarSex$`1` + evmarSex$`2`) 

evmarSex <- dcast(evmarSex, agecat~sex, value.var = "prop")

evmarSex %>% plot_ly(x=~agecat, y=~`F`, type='bar', name="Females") %>%
          add_trace(x=~agecat, y=~M, name="Males") %>%
          layout(yaxis = list(title="", barmode='group'), 
               xaxis = list(title=""), title="Ever Married or Cohabitated by Sex")
```

### By Race  
```{r evmar-race, echo=FALSE}
evmarRace <- suppressWarnings(svy %>% 
              group_by(agecat, race, EVMARCOH) %>% 
              summarize(count=survey_total()))
evmarRace <- dcast(evmarRace, agecat+race~EVMARCOH, value.var = "count")
evmarRace$prop <- evmarRace$`1` / (evmarRace$`1` + evmarRace$`2`) 
evmarRace <- dcast(evmarRace, agecat~race, value.var = "prop")

evmarRace %>% plot_ly(x=~agecat, y=~b, type='bar', name="Black") %>%
          add_trace(x=~agecat, y=~h, name="Hispanic") %>%
          add_trace(x=~agecat, y=~w, name="White") %>%
          add_trace(x=~agecat, y=~o, name="Other") %>%
          layout(yaxis = list(title="", barmode='group'), 
               xaxis = list(title=""), title="Ever Married or Cohabitated by Race")
```

## Currently Married or Cohabitating 

```{r curr-marcoh, echo=FALSE}

currmar <- suppressWarnings(svy %>%
            mutate(mcoh = ifelse((MARSTAT %in% "1" | MARSTAT %in% "2"), 1, 2)) %>%
            group_by(agecat, mcoh) %>%
            summarize(n = survey_total()))
currmar <- dcast(currmar, agecat~mcoh, value.var = "n")
currmar$prop <- currmar$`1` / (currmar$`1` + currmar$`2`)

currmar %>% plot_ly(x=~agecat, y=~prop, type='bar') %>%
          layout(yaxis = list(title="Proportion"), 
               xaxis = list(title="Age Category"), title="Currently Married or Cohabitating")

```


## Same-Sex Contacts
```{r sexpref, echo=FALSE}
ssany <- suppressWarnings(svy %>% 
          mutate(ssany = ifelse(SAMESEXANY %in% 1, 1,
                                ifelse((SAMESEXANY %in% 5 | SAMESEXANY %in% 7), 2, 0))) %>%
          group_by(agecat, sex, ssany) %>%
          summarize(n=survey_total()))

ssany <- dcast(ssany, agecat+sex~ssany, value.var = "n")
ssany$prop <- ssany$`1`/(ssany$`1` + ssany$`2`)
ssany <- dcast(ssany, agecat~sex, value.var = "prop")

ssany %>% plot_ly(x=~agecat, y=~`F`, type="bar", name="Females") %>%
          add_trace(x=~agecat, y=~M, type="bar", name="Males") %>%
          layout(title="Proportion Ever Had Same-Sex Contact", 
                 yaxis=list(title=""))

```
